name: Release

on:
  workflow_dispatch: 

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing commits & tags

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get full history & tags
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Commitizen
        run: pip install commitizen

      - name: Bump version & changelog
        run: python -m commitizen bump --yes --changelog

      - name: Push changes & tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push --follow-tags
          git push origin HEAD:main
